#!/bin/bash

# Clean user input.
# @param input.
function clean_input(){    
    local -n ref=$1; # Obtain the value of the pointed variable.

    text=${ref}; # Obtain the value of the referenced variable
    text=${text//_/}; # Strip underscores.
    text=${text// /_}; # Replace spaces with underscores.
    # Clean out anything that's not alphanumeric or an underscore.
    text=${text//[^a-zA-Z0-9_]/};
    text=`echo -n $text | tr A-Z a-z`; # Sring to lowercase.

    ref=${text}; # Copy handled text to pointed variable.

    return 0;
}

# Confirms project name.
function confirm_project_name(){
    echo -en "\e[32m>\e[0m Is \"$1\" correct? \e[2m(y/N)\e[0m ";
    read bool;
    bool=${bool:-No};
    case "$bool" in
        [yY]|[yY][eE][sS])
            ;;
        [nN]|[nN][oO])
            echo "User canceled project initialization.";
            exit 1;
            ;;
        *)
            ;;
    esac
}

# Replace common file project name.
# @param file.
function replace_project_name_in_file(){
    sed -i 's/program/'${PROJECT_NAME}'/g' $1;
    sed -i 's/Program/'${PROJECT_NAME^}'/g' $1;
    sed -i 's/PROGRAM/'${PROJECT_NAME^^}'/g' $1;
}

# Replace project name in tests/Makefile.am.
# @param file.
function handle_test_makefile(){
    sed -i 's/program_test/'${PROJECT_NAME}'_test/g' $1;
    sed -i 's/TEST_PROGRAM/TEST_'${PROJECT_NAME}'/g' $1;
    sed -i 's/libprogram/lib'${PROJECT_NAME}'/g' $1;
}

# Replace mail.
# @param file.
function replace_mail(){
    sed -i 's/user@mail.com/'${MAIL}'/g' $2;
}

# Check if name is given as argument.
if [ "$1" == "" ] ; then
    # Request project name.
    echo -en "\e[32m>\e[0m Introduce the name of the project: ";
    read PROJECT_NAME;
else
    # All arguments are setted as project name.
    PROJECT_NAME=$@;
fi;

# Request project author mail.
echo -en "\e[32m>\e[0m Introduce the mail of the author: ";
read MAIL;

# Clean user input.
clean_input PROJECT_NAME; # Passing reference of variable.

# Confirm project name.
confirm_project_name ${PROJECT_NAME};

echo -e "\e[32m>\e[0m Initializing project "${PROJECT_NAME}".";

replace_project_name_in_file include/program/program.h;
replace_project_name_in_file include/program/common.h;
replace_project_name_in_file include/program/util.h;
replace_project_name_in_file include/program/Makefile.am;
replace_project_name_in_file include/Makefile.am;

replace_project_name_in_file src/common.c;
replace_project_name_in_file src/main.c;
replace_project_name_in_file src/Makefile.am;
replace_project_name_in_file src/program.c;
replace_project_name_in_file src/util.c;

handle_test_makefile tests/Makefile.am;
replace_project_name_in_file tests/program_test.c;
replace_project_name_in_file tests/program_test.supp;
replace_project_name_in_file tests/util_test.c;
replace_project_name_in_file tests/util_test.supp;

replace_project_name_in_file .gitignore;
replace_project_name_in_file configure.ac;
replace_project_name_in_file Makefile.am;
replace_project_name_in_file README;
replace_project_name_in_file TODO;

replace_mail configure.ac;

mv include/program/program.h include/program/${PROJECT_NAME}.h
mv include/program include/${PROJECT_NAME}

mv src/program.c src/${PROJECT_NAME}.c

mv tests/program_test.c tests/${PROJECT_NAME}_test.c
mv tests/program_test.supp tests/${PROJECT_NAME}_test.supp

echo -e "\e[32m>\e[0m Finished project initialization.";

rm project_init